export const INIT_COMPANIES_LIST = 'INIT_COMPANIES_LIST'
export const INIT_EMPLOYEES_LIST = 'INIT_EMPLOYEES_LIST'
export const TOGGLE_ERROR_ALERT = 'TOGGLE_ERROR_ALERT'
export const TOGGLE_SUCCESS_ALERT = 'TOGGLE_SUCCESS_ALERT'
